name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test (Java 21)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew -Dorg.gradle.jvmargs="-Xmx2g" --no-daemon clean build jacocoTestReport -x test
        shell: bash
      - name: Test
        run: ./gradlew --no-daemon test jacocoTestReport
        shell: bash
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ runner.os }}
          path: build/reports/jacoco/test/html


