name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew
      - name: Build distributions
        run: ./gradlew --no-daemon clean build distZip
        shell: bash
      - name: Upload artifact (distZip)
        uses: actions/upload-artifact@v4
        with:
          name: beadmaker-dist
          path: build/distributions/*.zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


